[include]
files = [
    "src/animation.toml",
    "src/appearance.toml",
    "src/environment.toml",
    "src/general.toml",
    "src/input.toml",
    "src/keybinds.toml",
    "src/layout.toml",
    "src/outputs.toml",
    "src/overview.toml",
    "src/rules.toml",
    "src/workspaces.toml",
    "noctalia.toml"
]

[events]
lid_close = "notify-send 'lid closed'"
lid_open = "notify-send 'lid open'"
