[include]
files = [
    "src/bar/top.toml",
    "src/bar/widgets.toml",
    "src/desktop/widgets.toml",
    "src/dock.toml",
    "src/idle.toml",
    "src/lockscreen_widgets.toml",
    "src/osd.toml",
    "src/plugins.toml",
    "src/settings.toml",
    "src/shell.toml",
    "src/theme.toml",
    "src/wallpaper.toml",
    "src/notification.toml"
]
