[location]
address = "Minneapolis, MN"

[brightness]
enable_ddcutil = true

[weather]
unit = "Imperial"

[nightlight]
enabled = true
temperature_night = 5000

[backdrop]
enabled = true

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "screen_time"
