[shell]
font_family = "DejaVu Sans"
avatar_path = "~/pictures/avatars/avatar.jpg"
middle_click_opens_widget_settings = false

[shell.panel]
transparency_mode = "soft"
control_center_placement = "centered"
launcher_placement = "centered"
wallpaper_placement = "centered"
session_placement = "centered"

[shell.screenshot]
directory = "~/pictures/noctalia-screenshots"

[[shell.session.actions]]
action = "lock"
enabled = true
shortcut = "1"
variant = "default"

[[shell.session.actions]]
action = "logout"
enabled = true
shortcut = "2"
variant = "default"

[[shell.session.actions]]
action = "lock_and_suspend"
enabled = false
shortcut = "3"
variant = "default"

[[shell.session.actions]]
action = "reboot"
enabled = true
shortcut = "4"
variant = "default"

[[shell.session.actions]]
action = "shutdown"
enabled = true
shortcut = "5"
variant = "destructive"
