[shell]
app_icon_colorize = false
avatar_path = "/home/scottn/projects/dotfiles/icons/avatar.jpg"
clipboard_auto_paste = "ctrl_v"
clipboard_confirm_clear_history = true
clipboard_enabled = true
clipboard_history_max_entries = 100
clipboard_image_action_command = ""
corner_radius_scale = 1.0
date_format = "%A, %x"
disable_mipmaps = false
font_family = "sans-serif"
launch_apps_as_systemd_services = false
middle_click_opens_widget_settings = true
niri_overview_type_to_launch_enabled = false
offline_mode = false
password_style = "default"
polkit_agent = true
screen_time_enabled = false
settings_show_advanced = false
setup_wizard_enabled = true
shared_gl_context = true
show_location = true
telemetry_enabled = false
time_format = "{:%H:%M}"
ui_scale = 1.0

    [shell.animation]
    enabled = true
    speed = 1.5

    [shell.mpris]
    blacklist = []

    [shell.panel]
    borders = true
    clipboard_placement = "centered"
    control_center_placement = "attached"
    floating_offset = 8
    launcher_categories = true
    launcher_compact = true
    launcher_placement = "centered"
    launcher_session_search = false
    launcher_show_icons = true
    launcher_sort_by_usage = false
    open_near_click_clipboard = false
    open_near_click_control_center = false
    open_near_click_launcher = false
    open_near_click_session = false
    open_near_click_wallpaper = false
    session_placement = "attached"
    shadow = true
    transparency_mode = "solid"
    wallpaper_placement = "attached"

    [shell.screen_corners]
    enabled = false
    size = 32

    [shell.screenshot]
    copy_to_clipboard = true
    directory = "/home/scottn/pictures/noctalia-screenshots"
    filename_pattern = ""
    freeze_screen = true
    pipe_command = ""
    pipe_to_command = false
    save_to_file = true

    [shell.session.power]

    [[shell.session.actions]]
    action = "lock"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    command = ""
    enabled = true
