[theme]
background = "#1a110f"
primary = "#ffb4a3"
secondary = "#e7bdb4"
title = "#ffb4a3"
playing = "#dbc58c"
playing_bg = "#1a110f"
playing_selected = "#dbc58c"
highlight = "#f1dfdb"
highlight_bg = "#1a110f"
error = "#690005"
error_bg = "#ffb4ab"
statusbar = "#2c1510"
statusbar_progress = "#5d3f39"
cmdline = "#ffb4a3"
cmdline_bg = "#534340"
search_match = "#dbc58c"
