[appearance]
prefer_no_csd       = true
border_width        = 2
outer_border_width  = 0
corner_radius       = 6
drag_opacity        = 0.75

[appearance.blur]
enabled             = true
optimized           = true
passes              = 3
radius              = 3
noise               = 0.02
brightness          = 0.9
saturation          = 1.1

[appearance.shadow]
enabled             = true
softness            = 10
offset_x            = 2
offset_y            = 2
