[general]
autostart = [
    "noctalia",
    "~/.config/umbriel/submap-subscription.sh"
]

mod_key                 = "Super"
xwayland                = true
show_cheatsheet         = false
focus_on_activate       = false
honor_restored_maximize = false
