[general]
autostart = [
    "noctalia"
]

mod_key                 = "Super"
xwayland                = true
show_cheatsheet         = false
focus_on_activate       = false
honor_restored_maximize = false
