[keybinds]

# generics
"Mod+Return"                    = "spawn:alacritty"
"Mod+Shift+Minus"               = "cheatsheet-toggle"

# noctalia shell
"Mod+Period"                    = "spawn:noctalia msg panel-toggle launcher"
"Mod+I"                         = "spawn:noctalia msg panel-toggle control-center"
"Mod+Comma"                     = "spawn:noctalia msg settings-toggle"
"Mod+W"                         = "spawn:noctalia msg panel-toggle wallpaper"
"Mod+S"                         = "spawn:noctalia msg panel-toggle ahmedhossamdev/sticky-notes:panel"
"Mod+D"                         = "spawn:noctalia msg panel-toggle nightwatch75/todo:todo"
"Mod+F"                         = "spawn:noctalia msg panel-toggle davemhammer/obsidian:manager"
"Mod+G"                         = "spawn:noctalia msg panel-toggle nomadcxx/gamer-mode:main"
"Mod+U"                         = "spawn:noctalia msg panel-toggle noctalia/umbriel-companion:panel"
"Alt+Tab"                       = "spawn:noctalia msg window-switcher"
"Mod+Shift+Q"                   = "spawn:noctalia msg panel-toggle session"

# submaps
"Mod+N"                         = "spawn:wlr-which-key ~/.config/wlr-which-key/config-noctalia.yaml"
"Mod+C"                         = "spawn:~/.config/wlr-which-key/wlr-which-key-caller.sh"

# column manip
"Mod+Shift+H"                   = "column-move-left"
"Mod+Shift+L"                   = "column-move-right"
"Mod+Shift+J"                   = "column-move-to-workspace-next"
"Mod+Shift+K"                   = "column-move-to-workspace-previous"
"Mod+M"                         = "column-center"

# window manip
"Mod+Q"                         = "window-close"
"Mod+H"                         = "window-focus-left"
"Mod+L"                         = "window-focus-right"
"Mod+K"                         = "window-focus-up"
"Mod+J"                         = "window-focus-down"
"Mod+bracketleft"               = "window-consume-or-expel-left"
"Mod+bracketright"              = "window-consume-or-expel-right"
"Mod+R"                         = "window-cycle-primary-extent"
"Mod+T"                         = "window-cycle-secondary-extent"

# workspace manip
"Mod+Ctrl+J"                    = "workspace-next"
"Mod+Ctrl+K"                    = "workspace-previous"
"Mod+1"                         = "workspace-switch:1"
"Mod+2"                         = "workspace-switch:2"
"Mod+3"                         = "workspace-switch:3"
"Mod+4"                         = "workspace-switch:4"
"Mod+5"                         = "workspace-switch:5"

# output manip
"Mod+Alt+H"                     = "output-focus-left"
"Mod+Alt+L"                     = "output-focus-right"
"Mod+Alt+K"                     = "output-focus-up"
"Mod+Alt+J"                     = "output-focus-down"

# overview manip
"Mod+O"                         = "overview-toggle"

# scratchpad mapip
"Mod+Space"                     = "scratchpad-toggle"
"Mod+Shift+Space"               = "window-toggle-scratchpad"
"Mod+Tab"                       = "scratchpad-focus-next"

# volume control
"XF86AudioRaiseVolume"          = "spawn:noctalia msg volume-up 5"
"XF86AudioLowerVolume"          = "spawn:noctalia msg volume-down 5"
"XF86AudioMute"                 = "spawn:noctalia msg volume-mute"

# playback control
"XF86AudioPlay"                 = "spawn:playerctl play-pause"
"XF86AudioNext"                 = "spawn:playerctl next"
"XF86AudioPrev"                 = "spawn:playerctl previous"

# brightness control
"XF86MonBrightnessUp"           = "spawn:noctalia msg brightness-up 5"
"XF86MonBrightnessDown"         = "spawn:noctalia msg brightness-down 5"
