[layout]
gap                     = 8
width_presets           = [ 0.333, 0.5, 0.667 ]

[layout.struts]
left                    = 0
right                   = 0
top                     = 0
bottom                  = 0

[layout.scrolling]
default_width_fraction  = 0.5
center_underfull_strip  = true
center_focused          = false
expand_single_column    = false

[layout.dwindle]
preserve_split          = false

[layout.master]
position                = "left"
default_width_fraction  = 0.55
new_on_top              = true
