[control_center]
hidden_tabs             = [ "monitor", "bluetooth" ]
show_session_button     = false
show_shortcut_labels    = false
sidebar_section         = "none"

[[control_center.shortcuts]]
type                    = "noctalia/screen_recorder:toggle"

[[control_center.shortcuts]]
type                    = "mic_mute"

[[control_center.shortcuts]]
type                    = "power_profile"

[[control_center.shortcuts]]
type                    = "session"

[control_center.calendar]
show_events_card        = false
