[control_center]
hidden_tabs             = [ "monitor", "bluetooth" ]
show_session_button     = false
show_shortcut_labels    = false

[[control_center.shortcuts]]
type                    = "mic_mute"

[[control_center.shortcuts]]
type                    = "nightlight"

[[control_center.shortcuts]]
type                    = "notification"

[[control_center.shortcuts]]
type                    = "power_profile"

[[control_center.shortcuts]]
type                    = "session"

[control_center.calendar]
show_event_card         = false
