[theme]
builtin                     = "Eldritch"
community_palette           = "Everforest"
custom_palette              = ""
mode                        = "dark"
source                      = "wallpaper"
wallpaper_scheme            = "soft"

[theme.templates]
builtin_ids                 = [ "niri", "cava", "qt", "umbriel" ]
community_ids               = [ "brave-origin", "neovim", "obsidian", "steam", "papirus-icons", "yazi" ]
enable_builtin_templates    = true
enable_community_templates  = true

[theme.templates.user.alacritty]
input_path                  = "~/.config/noctalia/templates/alacritty.toml"
output_path                 = "~/.config/alacritty/themes/noctalia.toml"
enabled                     = true

[theme.templates.user.ncspot]
input_path                  = "~/.config/noctalia/templates/ncspot.toml"
output_path                 = "~/.config/ncspot/config.toml"
enabled                     = true

[theme.templates.user.starship]
input_path                  = "~/.config/noctalia/templates/starship.toml"
output_path                 = "~/.config/starship.toml"
enabled                     = true

[theme.templates.user.fuzzel]
input_path                  = "~/.config/noctalia/templates/fuzzel.ini"
output_path                 = "~/.config/fuzzel/themes/noctalia"
enabled                     = true

[theme.templates.user.fastfetch]
input_path                  = "~/.config/noctalia/templates/fastfetch.jsonc"
output_path                 = "~/.config/fastfetch/config.jsonc"
enabled                     = true

[theme.templates.user.obsidian_extra]
input_path                  = "~/.config/noctalia/templates/obsidian.css"
output_path                 = "~/documents/notes/main/.obsidian/snippets/noctalia.css"
enabled                     = true

[theme.templates.user.wlr-which-key-system]
input_path                  = "~/.config/noctalia/templates/wlr-which-key-system.yaml"
output_path                 = "~/.config/wlr-which-key/config-system.yaml"
enabled                     = true

[theme.templates.user.wlr-which-key-noctalia]
input_path                  = "~/.config/noctalia/templates/wlr-which-key-noctalia.yaml"
output_path                 = "~/.config/wlr-which-key/config-noctalia.yaml"
enabled                     = true

[theme.templates.user.wlr-which-key-niri]
input_path                  = "~/.config/noctalia/templates/wlr-which-key-niri.yaml"
output_path                 = "~/.config/wlr-which-key/config-niri.yaml"
enabled                     = true

[theme.templates.user.wlr-which-key-umbriel]
input_path                  = "~/.config/noctalia/templates/wlr-which-key-umbriel.yaml"
output_path                 = "~/.config/wlr-which-key/config-umbriel.yaml"
enabled                     = true
