[theme]
background = "{{ colors.background.default.hex }}"
primary = "{{ colors.primary.default.hex }}"
secondary = "{{ colors.secondary.default.hex }}"
title = "{{ colors.primary.default.hex }}"
playing = "{{ colors.tertiary.default.hex }}"
playing_bg = "{{ colors.background.default.hex }}"
playing_selected = "{{ colors.tertiary.default.hex }}"
highlight = "{{ colors.on_surface.default.hex }}"
highlight_bg = "{{ colors.background.default.hex }}"
error = "{{ colors.on_error.default.hex }}"
error_bg = "{{ colors.error.default.hex }}"
statusbar = "{{ colors.on_secondary_fixed.default.hex }}"
statusbar_progress = "{{ colors.on_secondary_fixed_variant.default.hex }}"
cmdline = "{{ colors.primary.default.hex }}"
cmdline_bg = "{{ colors.surface_variant.default.hex }}"
search_match = "{{ colors.tertiary.default.hex }}"
