[layout_constants]
top_bar_height      = 34

[font]
terminal            = "ZedMono NFM Extd"
terminal_size       = 11
widget_mono         = "JetBrainsMonoNL NFM"
menu                = "JetBrainsMonoNL NFM"
menu_size           = 14

[images]
avatar              = "~/pictures/images/icons/avatar.jpg"

[file]
bookmarks           = "~/documents/bookmarks/data.json"

[directory.document]
notes               = "~/documents/notes/main"
sticky_notes        = "~/documents/notes/main/sticky-notes"

[directory.media]
screen_recordings   = "~/videos/recordings"

[directory.wallpaper.dark]
wp3440              = "~/pictures/images/wallpapers/dark/3440x1440"
wp1920              = "~/pictures/images/wallpapers/dark/1920x1080"

[directory.wallpaper.light]
wp3440              = "~/pictures/images/wallpapers/light/3440x1440"
wp1920              = "~/pictures/images/wallpapers/light/1920x1080"

[wlr_which_key]
font                = "JetBrainsMonoNL NFM"
font_size           = 14
separator           = " :: "
border_width        = 2
border_radius       = 6
padding             = 18
rows_per_column     = 8
column_padding      = 16
anchor              = "center"
margin_left         = 0
margin_top          = 0
margin_right        = 0
margin_bottom       = 0
inhibit_comp        = "true"
auto_kdb_layout     = "true"

[[widget_definition]]
stat                = "cpu_freq"
name                = "dw-cpu-freq"

[[widget_definition]]
stat                = "cpu_usage"
name                = "dw-cpu-usage"

[[widget_definition]]
stat                = "cpu_temp"
name                = "dw-cpu-temp"

[[widget_definition]]
stat                = "gpu_vram"
name                = "dw-gpu-vram"

[[widget_definition]]
stat                = "gpu_usage"
name                = "dw-gpu-usage"

[[widget_definition]]
stat                = "gpu_temp"
name                = "dw-gpu-temp"

[[widget_definition]]
stat                = "ram_pct"
name                = "dw-ram-usage"

[[widget_definition]]
stat                = "swap_pct"
name                = "dw-swap-usage"
